# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images/brand_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images/slider_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SliderImageThumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images/slider_images/random_thumbs/')),
            ],
        ),
    ]
