# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-13 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visual_site_elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images/slider_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SliderImageThumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images/slider_images/random_thumbs/')),
            ],
        ),
        migrations.RemoveField(
            model_name='brandimage',
            name='brand',
        ),
        migrations.AddField(
            model_name='brandimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to='images/brand_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandimage',
            name='title',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
