# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 19:37
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visual_site_elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='images/brand_images'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='images/slider_images'),
        ),
        migrations.AlterField(
            model_name='sliderimagethumb',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='images/slider_images/random_thumbs'),
        ),
    ]
