version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  static-data: {}
  caddy: {}

services:
  postgres:
    restart: always
    build: ./compose/postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  django: &django
    restart: always
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: karnas/django
    container_name: django
    user: django
    depends_on:
      - postgres
      - redis
    volumes:
      - static-data:/static_root
    command: /gunicorn.sh
    env_file: .env

#  nginx:
#    restart: always
#    build: ./compose/nginx
#    container_name: nginx
#    depends_on:
#      - django
#    volumes:
#      - static-data:/static_root
#    volumes_from:
#      - django
#    ports:
#      - "0.0.0.0:80:80"
#      - "0.0.0.0:443:443"

  caddy:
    build:
      context: .
      dockerfile: ./compose/caddy/Dockerfile
    depends_on:
      - django
    volumes:
      - caddy:/root/.caddy
    env_file: .env
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    restart: always
    image: redis:latest
    container_name: redis

