# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django_images.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', max_length=255, upload_to=django_images.models.hashed_upload_to, width_field='width'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.ImageField(height_field='height', max_length=255, upload_to=django_images.models.hashed_upload_to, width_field='width'),
        ),
    ]
