# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(default=1, upload_to='images/portfolio_images'),
            preserve_default=False,
        ),
    ]
