# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='finished_date',
            field=models.DateField(null=True),
        ),
    ]
