# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20170131_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioShortIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('videowall', 'Videowall'), ('cctv', 'CCTV'), ('signage', 'Digital-Signage'), ('global', 'LG-Global')], default='Videowall', max_length=50),
        ),
    ]
