# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-31 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20170203_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-finished_date', 'title')},
        ),
    ]
