#!/usr/bin/env bash
set -e

# This allows us to use the same template
# for development, staging and production.
CONFIG_PATH="/etc/nginx/conf.d/default.conf"
STAGING_IP="139.162.141.212"
STAGING_HOSTNAME="do-staging"
DOMAIN_NAME="karnas.com.tr"

if [[ $(hostname) != "${STAGING_HOSTNAME}" ]]; then
  sed -i "s/${STAGING_IP}/${DOMAIN_NAME}/g" "${CONFIG_PATH}"
fi

# Execute the CMD from the Dockerfile.
exec "$@"
